### ISSUE TITLE
richer expect syntax for api calls

### ISSUE THREAD

**Issue by lukemarsden** [helixml/example-helix-app#4]
e.g
```
expect:
   - api_request:
       tool: "hr_saas"
       path: /jobvacancies/v1/list?candidate_name=Marcus
       method: GET
   - api_request:
       tool: "shop" # can be either ID or name
       path: /buy
       method: POST
       body_contains: "laptop"
```
